// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vimachem.Data;

#nullable disable

namespace Vimachem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vimachem.Models.Domain.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AuditLogId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditLogId"));

                    b.Property<string>("ActionType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Changes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AuditLogId");

                    b.ToTable("AuditLog");

                    b.HasData(
                        new
                        {
                            AuditLogId = 1,
                            ActionType = "Create",
                            Changes = "Initial creation of Fiction category",
                            EntityId = "1",
                            EntityType = "Category",
                            Timestamp = new DateTime(2024, 5, 2, 10, 50, 24, 711, DateTimeKind.Local).AddTicks(3563)
                        },
                        new
                        {
                            AuditLogId = 2,
                            ActionType = "Create",
                            Changes = "Initial creation of Non-Fiction category",
                            EntityId = "2",
                            EntityType = "Category",
                            Timestamp = new DateTime(2024, 5, 2, 10, 50, 24, 711, DateTimeKind.Local).AddTicks(3589)
                        });
                });

            modelBuilder.Entity("Vimachem.Models.Domain.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 5, 2, 10, 50, 24, 711, DateTimeKind.Local).AddTicks(3034),
                            Description = "Book 1 Description",
                            Name = "Book One"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 5, 2, 10, 50, 24, 711, DateTimeKind.Local).AddTicks(3045),
                            Description = "Book 2 Description",
                            Name = "Book Two"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 5, 2, 10, 50, 24, 711, DateTimeKind.Local).AddTicks(3047),
                            Description = "Book 3 Description",
                            Name = "Book Three"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 5, 2, 10, 50, 24, 711, DateTimeKind.Local).AddTicks(3049),
                            Description = "Book 4 Description",
                            Name = "Book Four"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2024, 5, 2, 10, 50, 24, 711, DateTimeKind.Local).AddTicks(3051),
                            Description = "Book 5 Description",
                            Name = "Book Five"
                        });
                });

            modelBuilder.Entity("Vimachem.Models.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 2, 10, 50, 24, 711, DateTimeKind.Local).AddTicks(1716),
                            Description = "This category encompasses a broad range of books that are primarily created from the imagination of the author. Fiction books may include novels, short stories, and novellas. Genres within fiction can vary widely, encompassing everything from historical fiction and fantasy to mystery, science fiction, and contemporary literature.",
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 2, 10, 50, 24, 711, DateTimeKind.Local).AddTicks(1795),
                            Description = "Non-fiction books are based on real facts and truthful accounts of events and ideas. This category includes biographies, memoirs, essays, and self-help books. Non-fiction also covers educational subjects such as history, psychology, science, and business.",
                            Name = "Non-Fiction"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 5, 2, 10, 50, 24, 711, DateTimeKind.Local).AddTicks(1797),
                            Description = "Books in this category are known for suspenseful plots that involve investigations and the solving of crimes. They often revolve around a mysterious event or a crime that needs to be solved, typically leading to a climactic reveal or twist.",
                            Name = "Mystery & Thriller"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 5, 2, 10, 50, 24, 711, DateTimeKind.Local).AddTicks(1798),
                            Description = "This category includes books that explore imaginative and futuristic concepts, alternative worlds, and advanced technology. Science fiction often deals with themes like space exploration and time travel, while fantasy books may include elements such as magic, mythical creatures, and medieval settings.",
                            Name = "Science Fiction & Fantasy"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 5, 2, 10, 50, 24, 711, DateTimeKind.Local).AddTicks(1800),
                            Description = "Romance books explore the theme of love and relationships between people. These stories often focus on romantic relationships from the courtship to the culmination of a love story, providing emotional narratives that may also delve into the characters’ personal growth.",
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 5, 2, 10, 50, 24, 711, DateTimeKind.Local).AddTicks(1802),
                            Description = "Designed to appeal to children from infancy through elementary school, these books range from picture books to easy readers and early chapter books. They often teach lessons through fun stories and vibrant illustrations, helping children understand their world and sparking their imagination.",
                            Name = "Children’s Books"
                        });
                });

            modelBuilder.Entity("Vimachem.Models.Domain.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Guest"
                        });
                });

            modelBuilder.Entity("Vimachem.Models.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alice",
                            Surname = "Johnson"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bob",
                            Surname = "Smith"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Charlie",
                            Surname = "Brown"
                        });
                });

            modelBuilder.Entity("Vimachem.Models.Domain.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Vimachem.Models.Domain.Book", b =>
                {
                    b.HasOne("Vimachem.Models.Domain.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Vimachem.Models.Domain.UserRole", b =>
                {
                    b.HasOne("Vimachem.Models.Domain.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vimachem.Models.Domain.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vimachem.Models.Domain.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Vimachem.Models.Domain.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
